#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service_oss
    #环境设置dev prod test
  profiles:
    active: dev

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4G5MWqPadEVgHGwDhHk9
      keysecret: zwCZkenEhBke2UcFhDUzaRpB18RiaY
#bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-guli0727
